name: Build JSON files from YAML

on:
  push:
    paths:
      - 'data/pt_BR.yaml'

  # enable manual run
  workflow_dispatch:

jobs:
  build:
    name: Convert YAML file to JSON and validates
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Run build command
        run: |
          npm install
          npm run build

      - name: Persist generated files
        run: |
          git config user.name 'Workflow: ${{ github.workflow }}'
          git config user.email ''
          git add -A
            git commit -m "${{ github.workflow }}"
          git push
